version: '2'

services:
  dockerregistry:
    image: registry:2
    ports:
      - "5000:5000"

  zookeeper:
    image: mesoscope/zookeeper
    environment:
      - SERVER_ID=mesoscope-zk
    ports:
      - "2181:2181"

