version: '2'

services:
  mesosslave:
    image: mesoscope/mesos-slave
    # links:
    #   - zookeeper:zookeeper
    #   - dockerregistry:dockerregistry
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MESOS_MASTER=zk://${IP_SERVICES_HOST}:2181/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_LOGGING_LEVEL=INFO
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
      - MESOS_WORK_DIR=/var/mesos
    ports:
      - "5051:5051"
      - "31000:31000"
      - "31001:31001"
      - "31002:31002"
      - "31003:31003"
      - "31004:31004"
      - "31005:31005"
      - "31006:31006"
      - "31007:31007"
      - "31008:31008"
      - "31009:31009"
    # networks:
    #   - "mesos_network"

networks:
  default:
    external:
       name: "mesos_network"
